version: '3'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      FRONTEND_PORT: 3000
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      BACKEND_PORT: 3001

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notesdb
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db